"""Paired bootstrap confidence intervals for external development AUC from saved predictions.

Real and generated images are resampled separately within each generator pairing,
with identical draws for every run, so differences between runs are paired.
Nothing is refit; this only quantifies uncertainty of already saved scores.
"""

import argparse
import csv
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
import numpy as np
from sklearn.metrics import roc_auc_score

from signalscope.paths import ROOT

PAIRS = {"guided": "imagenet", "ldm_200": "laion"}
SUFFIX = {"as_distributed": "", "matched": "_matched", "matched_native": "_matched_native"}
DEFAULT_RUNS = ["cifake_resnet18_robust_v1", "mixed_resnet18_v1", "mixed_resnet18_v2",
                "mixed_clip_b32_v1", "mixed_resnet18_native_v1"]


def load(run, protocol):
    path = ROOT / "report/predictions" / f"{run}_external_dev{SUFFIX[protocol]}.csv"
    if not path.exists():
        return None
    with path.open(encoding="utf-8", newline="") as stream:
        return {r["path"]: (r["domain"], int(r["label"]), float(r["ai_score"])) for r in csv.DictReader(stream)}


def interval(values):
    low, high = np.percentile(values, [2.5, 97.5])
    return [round(float(low), 4), round(float(high), 4)]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runs", nargs="+", default=DEFAULT_RUNS)
    parser.add_argument("--baseline", default="cifake_resnet18_robust_v1")
    parser.add_argument("--samples", type=int, default=2000)
    args = parser.parse_args()
    report = {"method": __doc__.strip(), "samples": args.samples, "seed": 2026, "baseline": args.baseline, "protocols": {}}
    lines = ["| Protocol | Run | Mean AUC | 95% CI | Difference vs baseline (95% CI) |", "|---|---|---:|---|---|"]
    for protocol in SUFFIX:
        loaded = {run: data for run in args.runs if (data := load(run, protocol))}
        if args.baseline not in loaded:
            continue
        paths = sorted(set.intersection(*(set(d) for d in loaded.values())))
        reference = loaded[args.baseline]
        groups = {}
        for generator, real in PAIRS.items():
            fakes = [p for p in paths if reference[p][0] == generator]
            reals = [p for p in paths if reference[p][0] == real]
            groups[generator] = (
                np.array([[loaded[r][p][2] for p in fakes] for r in loaded]),
                np.array([[loaded[r][p][2] for p in reals] for r in loaded]),
            )
        runs = list(loaded)
        rng = np.random.default_rng(2026)
        boot = np.zeros((args.samples, len(runs)))
        for b in range(args.samples):
            for fake_scores, real_scores in groups.values():
                fi = rng.integers(0, fake_scores.shape[1], fake_scores.shape[1])
                ri = rng.integers(0, real_scores.shape[1], real_scores.shape[1])
                labels = np.r_[np.ones(len(fi)), np.zeros(len(ri))]
                for k in range(len(runs)):
                    boot[b, k] += roc_auc_score(labels, np.r_[fake_scores[k, fi], real_scores[k, ri]]) / len(groups)
        point = []
        for k in range(len(runs)):
            aucs = []
            for fake_scores, real_scores in groups.values():
                labels = np.r_[np.ones(fake_scores.shape[1]), np.zeros(real_scores.shape[1])]
                aucs.append(roc_auc_score(labels, np.r_[fake_scores[k], real_scores[k]]))
            point.append(float(np.mean(aucs)))
        base = runs.index(args.baseline)
        report["protocols"][protocol] = {
            run: {"mean_auc": round(point[k], 4), "ci95": interval(boot[:, k]),
                  "difference_vs_baseline": round(point[k] - point[base], 4),
                  "difference_ci95": interval(boot[:, k] - boot[:, base]),
                  "images_per_generator": {g: [f.shape[1], r.shape[1]] for g, (f, r) in groups.items()}}
            for k, run in enumerate(runs)
        }
        for run, row in report["protocols"][protocol].items():
            lines.append(f"| {protocol} | {run} | {row['mean_auc']:.3f} | {row['ci95'][0]:.3f}-{row['ci95'][1]:.3f} | "
                         f"{row['difference_vs_baseline']:+.3f} ({row['difference_ci95'][0]:+.3f} to {row['difference_ci95'][1]:+.3f}) |")
    (ROOT / "report/external_bootstrap.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    (ROOT / "report/external_bootstrap.md").write_text(
        "# External development AUC uncertainty\n\nGenerated by `model/bootstrap_external.py` from saved "
        f"per-image predictions ({args.samples} paired stratified bootstrap samples). Development data only.\n\n"
        + "\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
