"""Tabulate saved development metrics for every candidate; never recomputes or tunes."""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from signalscope.paths import ROOT

RUNS = ROOT / "report/runs"


def load(run, *names):
    for name in names:
        path = RUNS / run / name / "metrics.json"
        if path.exists():
            return json.loads(path.read_text(encoding="utf-8"))
    return None


def pct(value):
    return "-" if value is None else f"{100 * value:.1f}%"


def auc(value):
    return "-" if value is None else f"{value:.3f}"


def main():
    rows = []
    for folder in sorted(p for p in RUNS.iterdir() if p.is_dir()):
        run = folder.name
        cifake = load(run, "cifake_val", "val")
        genimage = load(run, "genimage_val")
        external = {p: load(run, f"external_dev{s}") for p, s in (("as_distributed", ""), ("matched", "_matched"))}
        if not any([cifake, genimage, *external.values()]):
            continue
        hashes = {m.get("checkpoint_sha256") for m in [cifake, genimage, *external.values()] if m and m.get("checkpoint_sha256")}
        row = {
            "run": run,
            "checkpoint_hashes_consistent": len(hashes) <= 1,
            "cifake_val_auc": cifake and cifake["roc_auc"],
            "cifake_val_fpr": cifake and cifake["false_positive_rate"],
            "genimage_val_auc": genimage and genimage["roc_auc"],
            "genimage_val_fpr": genimage and genimage["false_positive_rate"],
            "genimage_per_source_auc": genimage and {k: v["roc_auc"] for k, v in genimage.get("per_source", {}).items()},
        }
        for protocol, report in external.items():
            by_generator = {g["generator"]: g for g in report["per_generator"]} if report else {}
            row[protocol] = report and {
                "mean_auc": report["macro_generator_roc_auc"],
                **{f"{g}_auc": m["roc_auc"] for g, m in by_generator.items()},
                **{f"{g}_real_fpr": m["false_positive_rate"] for g, m in by_generator.items()},
                **{f"{g}_ai_tpr": m["true_positive_rate"] for g, m in by_generator.items()},
            }
        rows.append(row)
    header = ("| Run | CIFAKE val AUC | GenImage val AUC | External mean AUC (as distributed) | Guided / LDM AUC | "
              "Real FPR ImageNet / LAION @0.5 | External mean AUC (matched) | Guided / LDM AUC (matched) | Real FPR (matched) |")
    lines = [header, "|" + "---|" * 9]
    for r in rows:
        a, m = r["as_distributed"] or {}, r["matched"] or {}
        lines.append(
            f"| {r['run']}{'' if r['checkpoint_hashes_consistent'] else ' (STALE HASH)'} | {auc(r['cifake_val_auc'])} | {auc(r['genimage_val_auc'])} | "
            f"{auc(a.get('mean_auc'))} | {auc(a.get('guided_auc'))} / {auc(a.get('ldm_200_auc'))} | "
            f"{pct(a.get('guided_real_fpr'))} / {pct(a.get('ldm_200_real_fpr'))} | {auc(m.get('mean_auc'))} | "
            f"{auc(m.get('guided_auc'))} / {auc(m.get('ldm_200_auc'))} | {pct(m.get('guided_real_fpr'))} / {pct(m.get('ldm_200_real_fpr'))} |"
        )
    table = "\n".join(lines)
    (ROOT / "report/candidate_comparison.json").write_text(json.dumps(rows, indent=2) + "\n", encoding="utf-8")
    (ROOT / "report/candidate_comparison.md").write_text(
        "# Development candidate comparison\n\nGenerated by `model/compare_candidates.py` from saved "
        "reports. Development data only; reserved GLIDE/DALLE and CIFAKE test are not included. "
        "FPR uses each checkpoint's stored threshold (0.5, uncalibrated unless stated).\n\n" + table + "\n",
        encoding="utf-8",
    )
    print(table)


if __name__ == "__main__":
    main()
