import { useState } from 'react'
import { Activity, ArrowUpRight, FlaskConical, Layers3 } from 'lucide-react'
import evidence from './release-evidence.json'

// Published measurements, never substituted for live API results or another model.
export function hasReleaseEvidence(model: { ready: boolean; checkpoint_sha256?: string; model_version?: string; threshold?: number } | null) {
  return !!model?.ready && model.checkpoint_sha256 === evidence.identity.checkpoint_sha256
    && model.model_version === evidence.model_version && model.threshold === evidence.identity.threshold
}
const source = 'https://github.com/sibtainmunshi/Signal_Scope/blob/4252d85/'
const pct = (n: number) => `${(100 * n).toFixed(1)}%`
const names: Record<string, string> = { original: 'Original', jpeg_q90: 'JPEG 90', jpeg_q70: 'JPEG 70', jpeg_q50: 'JPEG 50', jpeg_q30: 'JPEG 30', half_resolution: 'Half resolution', mild_blur: 'Mild blur', simulated_screenshot: 'Screenshot (sim.)' }

export function ReleaseEvidence() {
  const [selected, setSelected] = useState(2)
  const result = evidence.evaluations[selected]
  return <section className="release-evidence" aria-label="Published release evidence">
    <div className="section-title"><h2>Published release evidence</h2><span>v0.4.0 · CHECKPOINT MATCHED</span></div>
    <p className="muted release-context">Archived public-data measurements at the loaded model’s frozen threshold. These are separate from live service metrics and the unavailable organizer test. Holdout images were excluded from fitting; generator families overlap with training.</p>
    <section className="panel benchmark-panel">
      <div className="benchmark-toolbar"><div><span className="eyebrow">BENCHMARK EXPLORER</span><h2>{result.name}</h2></div><label>Evaluation set<select aria-label="Evaluation set" value={selected} onChange={event => setSelected(Number(event.target.value))}>{evidence.evaluations.map((item, index) => <option key={item.name} value={index}>{item.name} · {item.split}</option>)}</select></label></div>
      <div className="benchmark-stats">{[['ROC-AUC', result.roc_auc.toFixed(3)], ['Macro-F1', result.macro_f1.toFixed(3)], ['Accuracy', pct(result.accuracy)], ['Real-photo FPR', pct(result.false_positive_rate)]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
      <div className="benchmark-detail"><div><strong>{result.count.toLocaleString()} evaluated images</strong><p>{result.split} · {result.real_count.toLocaleString()} real / {result.ai_count.toLocaleString()} AI-generated.</p><p>AI images detected: <b>{pct(result.true_positive_rate)}</b>. ROC-AUC measures ranking; it is not percentage accuracy.</p><a href={source + 'report/experiments/mixed_clip_mlp_v2/results.json'} target="_blank" rel="noreferrer">View recorded measurements <ArrowUpRight size={14} /></a></div><table className="confusion-table"><caption>Confusion matrix · counts</caption><thead><tr><th scope="col">Actual ↓ / Predicted →</th><th scope="col">Real</th><th scope="col">AI</th></tr></thead><tbody><tr><th scope="row">Real</th><td>{result.confusion_matrix[0][0]}</td><td>{result.confusion_matrix[0][1]}</td></tr><tr><th scope="row">AI</th><td>{result.confusion_matrix[1][0]}</td><td>{result.confusion_matrix[1][1]}</td></tr></tbody></table></div>
      <div className="benchmark-caveat">Generalisation limit: these image holdouts are not a generator-disjoint test. Older guided/LDM development mean AUC fell to 0.637; the release failed its declared regression gate. No v0.4.0 GLIDE/DALLE reserve or organizer unseen-generator score is claimed.</div>
    </section>
    <details className="panel release-study"><summary><Activity size={19} /><span>Degradation & active defence<small>What changes after compression, resizing and blur</small></span><span className="study-indicator">Explore +</span></summary><div className="study-content"><p className="muted">783 GenImage validation images · a separate full-file robustness run. Accuracy and AI recall are shown together so missed AI images remain visible.</p><div className="degradation-key"><span>Accuracy</span><span>AI recall</span></div>{evidence.transformations.map(row => <div className="degradation-row" key={row.transformation}><span>{names[row.transformation]}</span><div className="degradation-bars" aria-hidden="true"><i style={{ width: pct(row.accuracy) }} /><b style={{ width: pct(row.true_positive_rate) }} /></div><strong>{pct(row.accuracy)}<small>{pct(row.true_positive_rate)}</small></strong></div>)}<p className="study-finding"><strong>{pct(evidence.active_defence.attack_success_rate)} attack success</strong> — {evidence.active_defence.successfully_flipped} of {evidence.active_defence.initially_correct} initially correct predictions flipped under a bounded search of seven transformations. This is a measured weakness, not adversarial robustness.</p><p className="muted">Screenshot results use synthetic resizing, window borders and PNG encoding, not a real device capture.</p><a href={source + 'report/experiments/robustness_v040/metrics.json'} target="_blank" rel="noreferrer">View robustness study <ArrowUpRight size={14} /></a></div></details>
    <details className="panel release-study"><summary><Layers3 size={19} /><span>Explanation faithfulness audit<small>40 development images · masking and attribution checks</small></span><span className="study-indicator">Explore +</span></summary><div className="study-content"><p className="study-finding"><strong>{evidence.explanation.supported}/{evidence.explanation.count} localised verdicts</strong> under the fixed masking rule. The highlighted-patch deletion advantage was not statistically significant (p = {evidence.explanation.mean_p.toFixed(2)} / {evidence.explanation.blur_p.toFixed(2)} for mean/blur masking).</p><p className="muted">This small development audit is not annotated-defect validation or a human usefulness review. Heatmaps show model influence; visible defects are not verified.</p><a href={source + 'report/explanation_audit/mixed_clip_mlp_v2_release/summary.json'} target="_blank" rel="noreferrer">View explanation audit <ArrowUpRight size={14} /></a></div></details>
    <div className="release-links"><a href={source + 'report/releases/v0.4.0/model_report.pdf'} target="_blank" rel="noreferrer"><FlaskConical size={16} /> One-page model report <ArrowUpRight size={14} /></a><a href={source + 'README.md'} target="_blank" rel="noreferrer">Setup, data sources & batch CLI <ArrowUpRight size={14} /></a></div>
  </section>
}
